version: 2

sources:
  - name: dbt_demo_sample
    schema: raw_sales
    tables:
      - name: customers
        description: "Raw customer data before cleaning/transformation"
        columns:
          - name: customer_id
            description: "Unique identifier for a customer"
            tests:
              - unique
              - not_null

      - name: sales
        description: "Raw sales data before cleaning/transformation"
        columns:
          - name: sale_id
            description: "Unique sale transaction ID"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Foreign key referencing customers"
            tests:
              - relationships:
                  to: source('dbt_demo_sample', 'customers')
                  field: customer_id

      - name: orders
        description: "Raw orders data before cleaning/transformation"
        columns:
          - name: order_id
            description: "Unique order ID"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Foreign key referencing customers"
            tests:
              - relationships:
                  to: source('dbt_demo_sample', 'customers')
                  field: customer_id


models:
  - name: stg_customers
    description: "Cleaned and deduplicated customer data"
    columns:
      - name: customer_id
        description: "Unique identifier for a customer"
        tests:
          - unique  
          - not_null  

      - name: email
        description: "Customer email, cleaned from empty values"
        tests:
          - not_null:
              severity: warn 

      - name: country
        description: "Customer country, replacing 'Unknown' with NULL"
        tests:
          - not_null:
              severity: warn 

      - name: created_at
        description: "Timestamp when the customer was created"
        tests:
          - not_null