name: 'dbt_demo'
version: '1.0.0'
config-version: 2
dbt-cloud:
    project-id: 70471823443633

profile: 'dbt_demo' 

# Paths for different dbt objects
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # Stores compiled SQL files
clean-targets:
  - "target"
  - "dbt_packages"

# Default materialization settings
models:
  dbt_demo:
      +materialized: table  